# -*- coding: utf-8 -*-
"""task-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hg6EShqg0YCcqxBBtpmy-6xbKrE23RDK

## File Organizer
"""

import os
import shutil

def organize_files(source_dir):
    # Define destination directories
    dest_dirs = {
        'Images': ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff', '.webp'],
        'Docs': ['.pdf', '.doc', '.docx', '.txt', '.rtf', '.xls', '.xlsx', '.ppt', '.pptx'],
        'Videos': ['.mp4', '.mkv', '.avi', '.mov', '.flv', '.wmv'],
        'Archives': ['.zip', '.rar', '.tar', '.gz', '.7z'],
        'Audio': ['.mp3', '.wav', '.aac', '.flac'],
        'Executables': ['.exe', '.dmg', '.app', '.deb', '.rpm'],
        'Code': ['.py', '.java', '.c', '.cpp', '.html', '.css', '.js']
    }

    # Create destination directories if they don't exist
    for folder_name in dest_dirs.keys():
        path = os.path.join(source_dir, folder_name)
        os.makedirs(path, exist_ok=True)

    # Create 'Others' directory
    others_path = os.path.join(source_dir, 'Others')
    os.makedirs(others_path, exist_ok=True)

    # Iterate through files in the source directory
    for filename in os.listdir(source_dir):
        # Skip directories and the created destination folders
        if os.path.isdir(os.path.join(source_dir, filename)) or filename in dest_dirs.keys() or filename == 'Others':
            continue

        file_path = os.path.join(source_dir, filename)
        file_extension = os.path.splitext(filename)[1].lower()

        moved = False
        for folder_name, extensions in dest_dirs.items():
            if file_extension in extensions:
                shutil.move(file_path, os.path.join(source_dir, folder_name, filename))
                print(f"Moved '{filename}' to '{folder_name}'")
                moved = True
                break

        if not moved:
            shutil.move(file_path, os.path.join(source_dir, 'Others', filename))
            print(f"Moved '{filename}' to 'Others'")


source_directory = './test_files'

# Create a dummy directory and some files for testing
print(f"Creating dummy files in {source_directory}...")
os.makedirs(source_directory, exist_ok=True)

# Create some dummy files
with open(os.path.join(source_directory, 'image.jpg'), 'w') as f: f.write('dummy content')
with open(os.path.join(source_directory, 'document.pdf'), 'w') as f: f.write('dummy content')
with open(os.path.join(source_directory, 'video.mp4'), 'w') as f: f.write('dummy content')
with open(os.path.join(source_directory, 'archive.zip'), 'w') as f: f.write('dummy content')
with open(os.path.join(source_directory, 'music.mp3'), 'w') as f: f.write('dummy content')
with open(os.path.join(source_directory, 'script.py'), 'w') as f: f.write('dummy content')
with open(os.path.join(source_directory, 'other.xyz'), 'w') as f: f.write('dummy content')

print("Organizing files...")
organize_files(source_directory)
print("File organization complete!")

#You can optionally delete the dummy files and directories after testing
shutil.rmtree(source_directory)
print(f"Cleaned up {source_directory}")